### ISSUE TITLE
peux-tu me créer un dépôt nommé tp-git-a-deux et y ajouter une branche develop s'il te plaît?

### ISSUE THREAD

**Issue by ghost** [Europerator/tp-git-a-deux#5]
peux-tu me créer un dépôt nommé tp-git-a-deux et y ajouter une branche develop s'il te plaît?

**Comment by Europerator** [comment]
Tu veux dire :
Dans le dépôt, créer un répertoire src. Ouvrir le temrinal dans ce répertoire et y créer une application C# Console en tapant la commande dotnet new console ?

**Comment by ghost** [comment]
Euh oui en fait
